#!/bin/bash

# Set ownership and permissions
chown dsf:dsf /opt/dsf/plugins/MotionWebcamServer.json
chmod 440 /opt/dsf/plugins/MotionWebcamServer.json

chown -R dsf:dsf /opt/dsf/plugins/MotionWebcamServer
chmod 550 /opt/dsf/plugins/MotionWebcamServer/dsf/arm/motion
chmod 550 /opt/dsf/plugins/MotionWebcamServer/dsf/arm64/motion

chown dsf:dsf /opt/dsf/sd/sys/motion.conf

# Reload the plugin manifest
if (systemctl is-active -q duetcontrolserver && systemctl is-active -q duetpluginservice-root); then
	# Don't wait for the plugin manager to return because that can lead to a deadlock if the install request came from the root plugin service
	if [[ -n `cat /opt/dsf/conf/plugins.txt | grep "^MotionWebcamServer$"` ]]; then
		(/opt/dsf/bin/PluginManager -q reload F3Plugin && /opt/dsf/bin/PluginManager -q start F3Plugin) &
	else
		/opt/dsf/bin/PluginManager -q reload F3Plugin &
	fi
fi

# Enable RPi webcam if applicable
if [ -f /usr/bin/raspi-config ]; then
	raspi-config nonint do_camera 0
fi

# Don't block the configuration of other packages if DPS failed to start
exit 0
