#!/bin/bash

# Kill the plugin first
killall F3Plugin || true
if ([[ -e /opt/dsf/conf/plugins.txt ]] && [[ "$1" != "upgrade" ]] && grep -q -e "^MotionWebcamServer$" /opt/dsf/conf/plugins.txt ); then
        sed -e '/^MotionWebcamServer$/d' -i /opt/dsf/conf/plugins.txt
fi

# Make manifest writable again
chmod 660 /opt/dsf/plugins/MotionWebcamServer.json

